/*
 * setup_main.c — PQ-ZK-eSIM offline setup tool
 *
 * Simulated registration kiosk：
 *   1. Read face features (preprocessed by gen_face_feature.py)
 *   2. Init eUICC nvram (keys, Merkle tree)
 *   3. Output registration data for server
 *
 * Run once. eUICC state is fixed afterward.
 * Then pqzkesim --auth for online auth.
 *
 * Usage:
 *   ./pqzkesim_setup --nvram /tmp/euicc \
 *                   --face features.bin \
 *                   --mno-id MNO_A_SIM_001
 */

#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <sys/stat.h>

#include "pq_zk_esim.h"
#include "pqzk_internal.h"
#include "pqzk_merkle.h"
#include "pqzk_cert.h"

int main(int argc, char *argv[])
{
    const char *nvram_dir    = "/tmp/pqzk_euicc";
    const char *feature_file = "features.bin";
    uint8_t mno_id[PQZK_MNO_ID_BYTES];
    memset(mno_id, 0, sizeof(mno_id));
    memcpy(mno_id, "MNO_A_SIM_001", 13);

    for (int i = 1; i < argc; i++) {
        if (!strcmp(argv[i], "--nvram")  && i+1 < argc)
            nvram_dir    = argv[++i];
        if (!strcmp(argv[i], "--face")   && i+1 < argc)
            feature_file = argv[++i];
        if (!strcmp(argv[i], "--mno-id") && i+1 < argc) {
            memset(mno_id, 0, sizeof(mno_id));
            strncpy((char*)mno_id, argv[++i], PQZK_MNO_ID_BYTES);
        }
    }

    printf("========================================\n");
    printf("  PQ-ZK-eSIM offline eUICC setup\n");
    printf("  Sim: kiosk activation\n");
    printf("========================================\n");
    printf("[Offline] nvram: %s\n", nvram_dir);
    printf("[Offline] feature file: %s\n", feature_file);
    printf("[Offline] operator: %.16s\n", (char*)mno_id);
    printf("\n");

    /* Check nvram already initialized */
    nvram_state_t check_state;
    if (nvram_read(nvram_dir, &check_state) == 0 &&
        check_state.tree_valid) {
        fprintf(stderr, "[Warn] eUICC already active, re-init will overwrite\n");
        fprintf(stderr, "       to re-activate, delete first %s\n", nvram_dir);
        fprintf(stderr, "       continue? (y/N): ");
        char ans = getchar();
        if (ans != 'y' && ans != 'Y') {
            printf("cancelled\n");
            return 0;
        }
    }

    mkdir(nvram_dir, 0700);

    /* Read face feature file */
    FILE *f = fopen(feature_file, "r");
    if (!f) {
        fprintf(stderr, "[Error] cannot read feature file: %s\n", feature_file);
        fprintf(stderr, "[Hint] run first:\n");
        fprintf(stderr, "       python3 tools/gen_face_feature.py"
                        " --img face.jpg --out features.bin\n");
        return -1;
    }

    int n_blocks;
    if (fscanf(f, "%d", &n_blocks) != 1 ||
        n_blocks <= 0 || n_blocks > PQZK_MERKLE_MAX_LEAVES) {
        fclose(f);
        fprintf(stderr, "[Error] feature file format error\n");
        return -1;
    }

    uint8_t (*features)[32] = malloc(n_blocks * 32);
    if (!features) { fclose(f); return -1; }

    for (int i = 0; i < n_blocks; i++)
        for (int j = 0; j < 32; j++) {
            unsigned int v;
            fscanf(f, "%02x", &v);
            features[i][j] = (uint8_t)v;
        }
    fclose(f);
    printf("[Offline] face features loaded, blocks:: %d\n", n_blocks);

    /*
     * Simulated OOB channel：
     * Real deployment：K_sym and k_tee generated by server, injected via NFC/USB
     * Simulated：generated locally, written to registration_data.bin
     */
    uint8_t k_sym[32], k_tee[32];
    pqzk_rand_bytes(k_sym, 32);
    pqzk_rand_bytes(k_tee, 32);
    printf("[Offline] Simulated OOB channel：K_sym、K_TEE generated\n");

    /* execute registration */
    uint8_t pk_t[PQ_ZK_PUBLICKEY_BYTES];
    uint8_t R_bio[32], salt[32];

    PQ_ZK_ErrorCode rc = PQC_Register(
        nvram_dir,
        (const uint8_t (*)[32])features, (size_t)n_blocks,
        k_sym, k_tee, 0,   /* initial_ctr = 0 */
        mno_id,
        pk_t, R_bio, salt);

    free(features);

    if (rc != PQ_ZK_SUCCESS) {
        fprintf(stderr, "[Error] eUICC init failed: %d\n", rc);
        return -1;
    }

    printf("[Offline] eUICC init complete\n");
    printf("[Offline] R_bio = ");
    for (int i = 0; i < 32; i++) printf("%02x", R_bio[i]);
    printf("\n");
    printf("[Offline] salt  = ");
    for (int i = 0; i < 32; i++) printf("%02x", salt[i]);
    printf("\n");

    /*
     * output registration data file
     * Real deployment：uploaded via OOB channel to server
     * Simulated：saved to file for backend Python scripts
     *           POST /api/v1/auth/register
     */
    FILE *reg = fopen("registration_data.bin", "wb");
    if (reg) {
        fwrite(pk_t,  1, PQ_ZK_PUBLICKEY_BYTES, reg);
        fwrite(R_bio, 1, 32, reg);
        fwrite(salt,  1, 32, reg);
        fwrite(k_sym, 1, 32, reg);
        fwrite(mno_id,1, PQZK_MNO_ID_BYTES, reg);
        fclose(reg);
    }

    printf("\n========================================\n");
    printf("  Offline setup complete\n");
    printf("  registration_data.bin generated\n");
    printf("  Submit this file to backend for server registration\n");
    printf("  Then run：./pqzkesim --auth --nvram %s\n", nvram_dir);
    printf("========================================\n");

    /* secure-zero sensitive data */
    secure_zero(k_sym, 32);
    secure_zero(k_tee, 32);

    return 0;
}
